# Site settings
title: The developer's den
email: --
description: > # this means to ignore newlines until "baseurl:"
  We all live in the developer's den
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bjansen.github.io" # the base hostname & protocol for your site
twitter_username: BastienJansen
github_username:  bjansen

# Build settings
highlighter: pygments
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      language: "fr"
      excerpt_separator: "<!-- more -->"